### ISSUE TITLE
No response received to location request

### ISSUE THREAD

**Issue by firmwareguru** [SkyhookWireless/embedded-client#5]
I've built a test project to send a location request packet to elg.skyhook.com, port 9755 over a TCP connection.  No response is received; the socket is closed shortly thereafter.  I suspect a potential malformed request packet.  However, there is no response sent by the server to help debug this.  Is there a way to determine what the problem is by looking at server responses?  Are there simple packet test cases that are known to generate responses?  Is there a test-vector byte array available?

**Comment by cdonais-skyhook** [comment]
Hi firmwareguru,

Yes, did you try building the demo with the supplied MAC addresses? Did you create an new ELG key on my.skyhookwireless.com? 

Please reach our to support@skyhook.com and we can help you further to diagnose the issue you are seeing.

Regards
Chris

**Comment by firmwareguru** [comment]
Hi Chris,

Success!  Using the canned values from the demo, it looks like we're in Needham Heights, as per this parsed location response:

timestamp: 0
protocol: 1
server version: 1
payload type no: 2
LOCATION_RQ_ADDR_SUCCESS
LOCATION_RQ
latitude: 42.2970
longitude: -71.2332
hpe: 70.0000
distance_to_point: 11.7336
Device MAC: n/a
LOCATION_RQ_ADDR
street num: 55
address: Manson Rd
city:
state: Massachusetts
state code: MA
postal code: 02494
county: Norfolk
country: United States
country code: US
metro1: Needham Heights
metro2: Needham
ip: n/a

To make this work, I need to keep polling the socket after it closed (or was indicated to be closed by the Wifi module).  It's to be expected that the lookup takes a few seconds.  The only confusing part was to keep polling for data even after the socket was closed.

A few details about my setup for anyone else attempting to do the same thing:
I'm working with an Cortex-M3 MCU (STM32L1) and a Wifi module (SPWF01), both from STMicro.  The ELG-common sources build mostly out of the box with the GNU toolchain.  

Note that the location response, and the use of Wifi as a location request transport, is a stop-gap communication system intended only for evaluating a wifi-based positioning system.  The real interesting part is the Skyhook "echo" service to forward the position to a cloud destination, as production version of these devices will be using a LPWAN link and don't really care about where they are.

Happy locating!

**Comment by firmwareguru** [comment]
Update! I have created a demonstration project that uses Skyhook's ELG service to perform real-time lookups.  Check it out at Hackster.io [here](https://www.hackster.io/firmwareguru/build-a-wifi-positioning-system-54a65d).
